### ISSUE TITLE
README

### ISSUE THREAD

**Issue by PipeManMusic** [dulnikovsky/magicstompfrenzy#1]
Can you include a README that includes compiling instructions I'd like to test.

**Comment by dulnikovsky** [comment]
If you are familiar with Qt then it's quite simple: run following commands:

1. Change to the project directory ( magicstompfrenzy )
2. run 'qmake magicstompfrenzy.pro'
3. run ' make -j4'

After that you will have the executable file "MagicstompFrenzy". Make sure you have Qt and ALSA development packages installed on Linux.
