### ISSUE TITLE
Compile Error QCommandLineParser: No such file or directory

### ISSUE THREAD

**Issue by PipeManMusic** [dulnikovsky/magicstompfrenzy#2]
Following the build instructions I got the following error compiling.

`g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG_OUTPUT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I../../magicstompfrenzy -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I../../magicstompfrenzy -I. -o main.o ../main.cpp
../main.cpp:25:10: fatal error: QCommandLineParser: No such file or directory
 #include <QCommandLineParser>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:899: main.o] Error 1
`

**Comment by PipeManMusic** [comment]
Figured it out, I didn't realize I had QT4 dev tools installed and obviously that created this issue, Sorry for the noise.

**Comment by dulnikovsky** [comment]
OK.
