### ISSUE TITLE
vcruntime140.dll missing windows 10

### ISSUE THREAD

**Issue by Guitarans** [dulnikovsky/magicstompfrenzy#4]
I have looked many places for fix my error, and installed some microsoft development tool stuff, but still can get it to work.
what software do i exactly need to make the software run. is there a link ? 
im not super at this :-)

**Comment by dulnikovsky** [comment]
Sorry to read your post so late. You need the Microsoft VS Redistributable: https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170&fbclid=IwAR2JlovRyQI-YR4Vf4npV0hELdniR69f-F9ctjlpOOoLtqfP5yV8WtNPPaw
